#!/bin/bash

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --cap-add=NET_ADMIN \
    --publish 127.0.0.1:1081:1080 \
    --volume "$(realpath "$1"):/ovpn.conf:ro" \
    mook/openvpn-client-socks:${TAG:-latest}
